osx_image: xcode7
language: objective-c
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
before_install:
  - brew update;
  - brew reinstall xctool
  - gem install cocoapods
  - gem install slather -N
  - xcrun simctl list
install: echo "<3"
env:
  - MODE=build
  - MODE=examples
script: ./build.sh $MODE
after_success: slather

# whitelist
branches:
  only:
    - master
